### PR TITLE
Fix module name and imports

### PR DESCRIPTION
**Pull request by atreya2011**
I noticed that the module name and imports were not updated to `grpc-ecosystem` and fixed it in all the appropriate files. 
Let me know if I have missed anything 🙏🏼

### CODE REVIEW

**Review by lyonlai — APPROVED** [review]
Thanks for this.

**Comment by lyonlai** [comment]
do you see the test for this? @atreya2011

**Comment by lyonlai** [comment]
@atreya2011 I've just updated the github action to run test on pull request. please rebase and give it a try

**Comment by atreya2011** [comment]
@lyonlai Thank you for your approval. Unfortunately, I am unable to see the tests 😓

**Comment by atreya2011** [comment]
@lyonlai Upon rebasing I can see the tests. Thanks for this 🙏🏼

**Pull request merged**
