### PR TITLE
Throw error object on HTTP error

### LINKED ISSUE #15: Handling errors
The fetch function seems to ignore the .ok status of the fetch response. This means that if there is a gRPC error, data is returned of the error type instead of the declared response type.

Shouldn’t the fetch function throw in case of http errors (I.e. if .ok is false), so the client can catch errors? (And so there is no typing inconsistency)

### PR DESCRIPTION
**Pull request by remko**
Fixes #15

### CODE REVIEW

**Review by lyonlai — CHANGES_REQUESTED** [review]
Can you try to put a test in to cover this case? in the `integration-test` folder.

**Comment by remko** [comment]
I wouldn't mind, but I can't get the tests to run (I'm trying a version without my changes). When running `./scripts/test.sh`, the test seems to hang once connected to Chrome Headless. Below is the debug output, if you have any clue, that would be helpful.

```
22 05 2021 20:44:40.516:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
22 05 2021 20:44:40.517:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
22 05 2021 20:44:40.520:INFO [launcher]: Starting browser ChromeHeadless
22 05 2021 20:44:40.521:DEBUG [launcher]: null -> BEING_CAPTURED
22 05 2021 20:44:40.521:DEBUG [temp-dir]: Creating temp dir at /var/folders/vp/8sjpl6t12js61l1cv4lyn4z80000gn/T/karma-19976205
22 05 2021 20:44:40.521:DEBUG [launcher]: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --user-data-dir=/var/folders/vp/8sjpl6t12js61l1cv4lyn4z80000gn/T/karma-19976205 --enable-automation --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate --disable-background-timer-throttling --disable-renderer-backgrounding --disable-device-discovery-notifications http://localhost:9876/?id=19976205 --headless --disable-gpu --disable-dev-shm-usage --remote-debugging-port=9222
22 05 2021 20:44:40.844:DEBUG [web-server]: serving: /Users/remko/Downloads/src/protoc-gen-grpc-gateway-ts/integration_tests/node_modules/karma/static/client.html
22 05 2021 20:44:40.911:DEBUG [web-server]: serving: /Users/remko/Downloads/src/protoc-gen-grpc-gateway-ts/integration_tests/node_modules/karma/static/karma.js
22 05 2021 20:44:40.943:DEBUG [karma-server]: A browser has connected on socket NUbHP8cd5yHL5zpwAAAA
22 05 2021 20:44:40.975:DEBUG [web-server]: upgrade /socket.io/?EIO=3&transport=websocket&sid=NUbHP8cd5yHL5zpwAAAA
22 05 2021 20:44:41.005:DEBUG [Chrome Headless 90.0.4430.212 (Mac OS 10.15.7)]: undefined -> CONNECTED
22 05 2021 20:44:41.005:INFO [Chrome Headless 90.0.4430.212 (Mac OS 10.15.7)]: Connected on socket NUbHP8cd5yHL5zpwAAAA with id 19976205
22 05 2021 20:44:41.006:DEBUG [launcher]: BEING_CAPTURED -> CAPTURED
22 05 2021 20:44:41.006:DEBUG [launcher]: ChromeHeadless (id 19976205) captured in 0.489 secs
```

**Comment by lyonlai** [comment]
that's odd. hmm. it was running ok before. I hit the same issue. use the `./script/test-ci.sh` instead. I'll take a look separately.

**Comment by lyonlai** [comment]
Also if you open the link in browser and hit the `Debug` button to open the debug page the test actually runs.

**Comment by remko** [comment]
@lyonlai Thanks for the tip! Updated the PR.

**Review by lyonlai — APPROVED** [review]
awesome, thanks for this. merging it.

**Pull request merged**
