### PR TITLE
Bumped protobuf version to v1.26

### PR DESCRIPTION
**Pull request by vgarvardt**
Bumped `google.golang.org/protobuf` and its dependency `github.com/golang/protobuf` to current latest stable versions.

### CODE REVIEW

**Comment by vgarvardt** [comment]
@googlebot I signed it!

**Comment by lyonlai** [comment]
is there any particular fixes that impacts you? @vgarvardt

**Comment by vgarvardt** [comment]
This PR was supposed to solve an issue that I have with gradle task that generates code for several languages. After adding TypeScript the task started to fail with the following error message:

```
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: 2021/06/15 22:38:34 WARNING: Malformed 'go_package' option in "acme/type/iso_week_date.proto", please specify:
  	option go_package = "github.com/acme/schema-registry-go/type;__type";
  A future release of protoc-gen-go will reject this.
```

Given that I recently bumped `protoc-gen-go` version to 1.26 and it has `go_package` related changes my hypothesis was that ts generator does not work well because of the older version of the library used in its deps.

After doing more tests - both running `protoc` with plugins manually and with gradle tasks I found out that actually something is wrong with gradle task error output - with all other plugins disabled the error makes much more sense:

```
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: acme/type/iso_week_date.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-grpc-gateway-ts hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--grpc-gateway-ts_out: 
```

I will create an issue regarding `optional` support for the generator.

This PR does not make a lot of sense so far and can be closed, unless you want to keep main deps up to date for the future release.

**Comment by lyonlai** [comment]
ah, right. it doesn't make much of a difference so I'll close this PR for now.

**Pull request closed without merging**
